Add closeOnClick property
weweb-assets/ww-hover-dropdown pull request #1
Opened 2022-01-25 18:25 UTC by AlexisJC

[Ticket WW-403](https://weweb.atlassian.net/browse/WW-403)

Bienvenue sur ma première PR !

L'idée était de permettre de garder la dropdown ouverte au click dans le contenu, pour certains cas de figure.

Il y avait plusieurs manières de procéder, j'ai préféré ajouter un nouvel état pour savoir si on avait la souris sur le contenu et conserver la femeture au click sur l'élément principal dans tous les cas.

2022-01-26 10:48 UTC, AurelieV approved these changes

2022-01-26 10:52 UTC, AurelieV requested changes
Check on mobile

2022-01-27 13:45 UTC, AurelieV commented on src/wwElement.vue
> +            immediate: true,
vu qu'on touche au dom, ça me paraisait justifier de pas passer par immediate true, mais de doubler cette action dans le mounted (sinon ca peut être executer trop tôt. Ici ca fo,ctionne car on dépends de document plutôt que de $el (qui n'existe pas), mais c'est une bonne pratique à garder pour être un jour ssr compliant

2022-01-28 09:41 UTC, AurelieV approved these changes

2022-01-28 10:47 UTC, Dams-d approved these changes

2022-01-28 10:58 UTC, AurelieV commented on src/wwElement.vue
> +                        v-if="isVisible || isContentEdit"
il n'y a pas une distinction mobile/pas mobile ?

2022-01-28 10:58 UTC, AurelieV commented on src/wwElement.vue
> -        'content.trigger'() {
on ne watch plus le trigger?

2022-01-31 13:07 UTC, merged